'use client'

import { useQuery } from '@tanstack/react-query'
import { superadminApi } from '@/lib/api'
import { LoadingSpinner } from '@/components/shared/loading-spinner'
import { StatsCard } from '@/components/shared/stats-card'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { DollarSign, TrendingUp, Users, Percent } from 'lucide-react'

export default function FinancialAnalyticsPage() {
  const { data: analytics, isLoading } = useQuery({
    queryKey: ['superadmin', 'financial-analytics'],
    queryFn: async () => {
      const response = await superadminApi.getFinancialAnalytics()
      return response.data
    },
  })

  if (isLoading) {
    return <LoadingSpinner />
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold">Financial Analytics</h1>
        <p className="text-muted-foreground mt-2">
          Detailed financial insights and performance metrics
        </p>
      </div>

      {/* Key Metrics */}
      <div className="grid gap-4 md:grid-cols-4">
        <StatsCard
          title="Total Revenue"
          value={`$${(analytics?.totalRevenue || 0).toLocaleString()}`}
          description="All-time"
          icon={DollarSign}
        />
        <StatsCard
          title="Payment Success Rate"
          value={`${analytics?.paymentSuccessRate || 0}%`}
          description="Successful payments"
          icon={Percent}
        />
        <StatsCard
          title="Average Revenue/Student"
          value={`$${analytics?.avgRevenuePerStudent || 0}`}
          description="Per student"
          icon={Users}
        />
        <StatsCard
          title="Growth Rate"
          value="+25%"
          description="Month over month"
          icon={TrendingUp}
        />
      </div>

      {/* Revenue per Batch */}
      <Card>
        <CardHeader>
          <CardTitle>Revenue per Batch</CardTitle>
          <CardDescription>Income breakdown by batch</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {analytics?.revenuePerBatch && analytics.revenuePerBatch.length > 0 ? (
            analytics.revenuePerBatch.map((batch: any) => {
              const percentage = (batch.revenue / (analytics.totalRevenue || 1)) * 100
              return (
                <div key={batch.batch_id} className="space-y-2">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-medium">{batch.batch_name}</p>
                      <p className="text-sm text-muted-foreground">{batch.student_count} students</p>
                    </div>
                    <div className="text-right">
                      <p className="text-lg font-bold text-green-600">${batch.revenue.toLocaleString()}</p>
                      <p className="text-sm text-muted-foreground">{percentage.toFixed(1)}%</p>
                    </div>
                  </div>
                  <Progress value={percentage} />
                </div>
              )
            })
          ) : (
            <p className="text-sm text-muted-foreground">No batch data available</p>
          )}
        </CardContent>
      </Card>

      {/* Revenue per Trainer */}
      <Card>
        <CardHeader>
          <CardTitle>Revenue per Trainer</CardTitle>
          <CardDescription>Income generated by each trainer's students</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {analytics?.revenuePerTrainer && analytics.revenuePerTrainer.length > 0 ? (
            analytics.revenuePerTrainer.map((trainer: any) => {
              const percentage = (trainer.revenue / (analytics.totalRevenue || 1)) * 100
              return (
                <div key={trainer.trainer_id} className="space-y-2">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-medium">{trainer.trainer_name}</p>
                      <p className="text-sm text-muted-foreground">{trainer.student_count} students</p>
                    </div>
                    <div className="text-right">
                      <p className="text-lg font-bold text-green-600">${trainer.revenue.toLocaleString()}</p>
                      <p className="text-sm text-muted-foreground">{percentage.toFixed(1)}%</p>
                    </div>
                  </div>
                  <Progress value={percentage} />
                </div>
              )
            })
          ) : (
            <p className="text-sm text-muted-foreground">No trainer data available</p>
          )}
        </CardContent>
      </Card>

      {/* Payment Success Metrics */}
      <Card>
        <CardHeader>
          <CardTitle>Payment Success Metrics</CardTitle>
          <CardDescription>Payment completion and failure analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-3">
            <div className="text-center p-4 border rounded-lg">
              <p className="text-3xl font-bold text-green-600">{analytics?.paymentSuccessRate || 0}%</p>
              <p className="text-sm text-muted-foreground mt-1">Success Rate</p>
            </div>
            <div className="text-center p-4 border rounded-lg">
              <p className="text-3xl font-bold">{analytics?.totalPayments || 0}</p>
              <p className="text-sm text-muted-foreground mt-1">Total Payments</p>
            </div>
            <div className="text-center p-4 border rounded-lg">
              <p className="text-3xl font-bold text-red-600">{analytics?.failedPayments || 0}</p>
              <p className="text-sm text-muted-foreground mt-1">Failed Payments</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

